import type { DesktopApiGateway } from '../shared/desktop-api-gateway';
import { createDesktopWorkbenchCenterPaneCoordinationInput } from './desktop-workbench-center-pane-handoffs';
import { createDesktopWorkbenchCenterPaneCoordinationProps } from './desktop-workbench-center-pane-coordination';
import { createDesktopWorkbenchOverlayCoordinationProps } from './desktop-workbench-overlay-coordination';
import { createDesktopWorkbenchOverlayCoordinationInput } from './desktop-workbench-overlay-handoffs';
import { createDesktopWorkbenchPreviewCoordinationInput } from './desktop-workbench-preview-coordination';
import { createDesktopWorkbenchTopbarCoordinationProps } from './desktop-workbench-topbar-coordination';
import { createDesktopWorkbenchTopbarCoordinationInput } from './desktop-workbench-topbar-handoffs';
import { createDesktopWorkbenchWorkspaceSettingsCoordinationInput } from './desktop-workbench-workspace-settings-coordination';
import { createDesktopWorkbenchShellCoordinationInput } from './desktop-workbench-shell-handoffs';
import { useAssetCommandFlowWorkbench } from './use-asset-command-flow-workbench';
import { useDesktopWorkbenchShellResources } from './use-desktop-workbench-shell-resources';
import { useDesktopWorkbenchShellCoordination } from './use-desktop-workbench-shell-coordination';
import { useDiagnosticsWorkbench } from './use-diagnostics-workbench';
import { useGalleryBrowsingWorkbench } from './use-gallery-browsing-workbench';
import { useGallerySettingsWorkbench } from './use-gallery-settings-workbench';
import { useGallerySessionWorkbench } from './use-gallery-session-workbench';
import { usePreviewWorkbench } from './use-preview-workbench';
import { useWorkspaceCommandsWorkbench } from './use-workspace-commands-workbench';
import { useWorkspaceGalleryLifecycleWorkbench } from './use-workspace-gallery-lifecycle-workbench';
import { useWorkspaceRuntimeStateWorkbench } from './use-workspace-runtime-state-workbench';
import { useWorkspaceSettingsWorkbench } from './use-workspace-settings-workbench';
import { useWorkspaceStateWorkbench } from './use-workspace-state-workbench';

interface UseDesktopWorkbenchOptions {
  desktopApi: DesktopApiGateway;
  isDevEnv: boolean;
  logoSrc: string;
}

export const useDesktopWorkbench = ({
  desktopApi,
  isDevEnv,
  logoSrc,
}: UseDesktopWorkbenchOptions) => {
  const {
    domRefs: {
      appShellRef,
      galleryScrollRef,
      gallerySizeSliderRef,
      listContainerRef,
      profileFormRefs,
      profileMenuButtonRef,
      profileMenuListRef,
      searchInputRef,
      uploadToastRef,
    },
    feedback: {
      copiedLabel,
      dismissStatusLine,
      inlineFeedback,
      markCopied,
      pushInlineFeedback,
      setStatusLine,
      status,
      statusTone,
    },
    isTooltipWarm,
  } = useDesktopWorkbenchShellResources();

  const {
    allowStoredSecret,
    canSaveProfile,
    closeProfileMenu,
    handleAppearanceChange,
    handleDefaultConflictPolicyChange,
    handlePresignedUrlTTLSecondsChange,
    handleSelectedPublicBaseUrlChange,
    handleUploadOptimizeImagesBeforeUploadChange,
    initialProfileForm,
    isConnectionSetupOpen,
    isCreatingProfile,
    isProfileBusy,
    isProfileFormDirty,
    isProfileMenuOpen,
    isSettingsBusy,
    isSettingsDirty,
    isShortcutHelpOpen,
    isWorkspaceSettingsOpen,
    manageProfileOptionValue,
    moveProfileMenuActiveIndex,
    newSavedViewName,
    newProfileOptionValue,
    openProfileMenu,
    profileFieldErrors,
    profileForm,
    profileFormValidationErrors,
    profileMenuActiveIndex,
    profileMenuOptions,
    profiles,
    r2AccountId,
    savedSettingsSnapshot,
    savedViews,
    selectedProfile,
    selectedProfileId,
    selectedProfileLabel,
    selectedPublicBaseUrl,
    setIsConnectionSetupOpen,
    setIsCreatingProfile,
    setIsProfileBusy,
    setIsSettingsBusy,
    setIsShortcutHelpOpen,
    setIsWorkspaceSettingsOpen,
    setNewSavedViewName,
    setProfileForm,
    setProfileMenuActiveIndex,
    setProfiles,
    setR2AccountId,
    setSavedSettingsSnapshot,
    setSavedViews,
    setSelectedProfileId,
    setSettings,
    settings,
  } = useWorkspaceStateWorkbench();

  const {
    activeKindFilter,
    activeKindLabel,
    activeSearchQuery,
    activeSmartCollection,
    activeSmartCollectionLabel,
    activeUnifiedFilterId,
    adjustGalleryTileMinWidth,
    applyGalleryTileMinWidth,
    assetItemRefs,
    assetsPrefix,
    assetsResult,
    commitGalleryTileMinWidth,
    flushGalleryTileMinWidthCommit,
    focusAssetItemByKey,
    galleryColumnCount,
    galleryDaySections,
    galleryGridLocationByKey,
    galleryThumbnailErrors,
    galleryThumbnailLoading,
    galleryThumbnails,
    galleryTileHeight,
    galleryTileMinWidth,
    galleryVirtualRange,
    galleryVirtualSections,
    galleryViewportHeight,
    handleLoadFirstPage,
    handleLoadNextPage,
    handleOpenPrefix,
    handleResetViewFilters,
    handleSearchClear,
    handleSearchSubmit,
    handleSelectUnifiedFilter,
    handleThumbnailDecodeError,
    isBrowserBusy,
    isGalleryScrolling,
    isPreviewableKind,
    isSearchBusy,
    isSelectionMode,
    listVirtualItems,
    listVirtualRange,
    loadAssetsPage,
    markAssetAsRecentlyViewed,
    nextAssetsContinuationToken,
    previewMediaItems,
    queueGalleryScrollStateUpdate,
    queueListScrollStateUpdate,
    reloadCurrentItems,
    requestThumbnailRetry,
    resetAssetsResult,
    resetGalleryThumbnails,
    resetGalleryTileMinWidth,
    resetSearchState,
    resolvePersistedUiStateForProfile,
    runSearch,
    scheduleGalleryTileMinWidthCommit,
    scrollToAssetInCurrentView,
    searchInput,
    selectedAsset,
    selectedAssetCount,
    selectedAssetKey,
    selectedAssetKeys,
    selectedAssetKeySet,
    selectedPreviewItemIndex,
    setActiveSearchQuery,
    setAssetItemRef,
    setAssetsPrefix,
    setGalleryScrollTop,
    setGalleryTileMinWidth,
    setIsSearchBusy,
    setIsSelectionMode,
    setKindFilter,
    setListScrollTop,
    setSearchInput,
    setSearchItems,
    setSelectedAssetKey,
    setSelectedAssetKeys,
    setSmartCollection,
    setSortBy,
    setSortDirection,
    setViewMode,
    sortBy,
    sortDirection,
    unifiedFilterOptions,
    viewMode,
    visibleGallerySections,
    visibleItems,
  } = useGalleryBrowsingWorkbench({
    appShellRef,
    assetDiscoveryApi: desktopApi.assetDiscovery,
    assetLibraryApi: desktopApi.assetLibrary,
    galleryScrollRef,
    gallerySizeSliderRef,
    listContainerRef,
    searchInputRef,
    selectedProfileId,
    setStatusLine,
  });

  const {
    closeQuickPreview,
    handleCopyToClipboard,
    isQuickPreviewOpen,
    moveQuickPreviewSelection,
    openQuickPreviewForItem,
    quickPreviewOverlayInput,
    setIsQuickPreviewOpen,
  } = usePreviewWorkbench(
    createDesktopWorkbenchPreviewCoordinationInput({
      api: {
        assetPreviewApi: desktopApi.assetLibrary,
        sharingApi: desktopApi.assetSharing,
      },
      feedback: {
        copiedLabel,
        markCopied,
        pushInlineFeedback,
        setStatusLine,
      },
      gallery: {
        assetItemRefs,
        focusAssetItemByKey,
        isPreviewableKind,
        markAssetAsRecentlyViewed,
        previewMediaItems,
        scrollToAssetInCurrentView,
        selectedPreviewItemIndex,
        setSelectedAssetKey,
      },
      previewState: {
        isConnectionSetupOpen,
        isSelectionMode,
        selectedAsset,
        selectedAssetKey,
      },
      profile: {
        presignedUrlTTLSeconds: settings.presignedUrlTTLSeconds,
        selectedAssetMetadataPublicBaseUrl: selectedPublicBaseUrl,
        selectedProfileId,
      },
    }),
  );

  const {
    handleProfileDeleted,
    handleProfileSelected,
  } = useWorkspaceGalleryLifecycleWorkbench({
    resetAssetsResult,
    setActiveSearchQuery,
    setSearchInput,
    setSearchItems,
    setSelectedAssetKey,
  });

  const {
    pendingDiscardConfirmation,
    cancelDiscardConfirmation,
    confirmDiscardChanges,
    handleCloseConnectionSetup,
    handleCloseShortcutHelp,
    handleCloseWorkspaceSettings,
    handleConnectionTest,
    handleDeleteProfile,
    handleOpenConnectionSetup,
    handleProfileMenuSelect,
    handleR2AccountIdChange,
    handleSaveProfile,
    handleSaveSettings,
    handleSelectProfile,
    handleStartNewProfile,
    handleToggleShortcutHelp,
    handleToggleWorkspaceSettings,
    hasInitialized,
    loadSavedViews,
  } = useWorkspaceCommandsWorkbench({
    assetDiscoveryApi: desktopApi.assetDiscovery,
    closeProfileMenu,
    initialProfileForm,
    isConnectionSetupOpen,
    isCreatingProfile,
    isProfileBusy,
    isProfileFormDirty,
    isProfileMenuOpen,
    isSettingsBusy,
    isSettingsDirty,
    isWorkspaceSettingsOpen,
    manageProfileOptionValue,
    newProfileOptionValue,
    profileForm,
    profileFormValidationErrors,
    profileFormRefs,
    profileMenuButtonRef,
    profileMenuListRef,
    profiles,
    onProfileDeleted: handleProfileDeleted,
    onProfileSelected: handleProfileSelected,
    pushInlineFeedback,
    savedSettingsSnapshot,
    selectedProfile,
    selectedProfileId,
    setIsConnectionSetupOpen,
    setIsCreatingProfile,
    setIsProfileBusy,
    setIsSettingsBusy,
    setIsShortcutHelpOpen,
    setIsWorkspaceSettingsOpen,
    setProfileForm,
    setProfiles,
    setR2AccountId,
    setSavedSettingsSnapshot,
    setSavedViews,
    setSelectedProfileId,
    setSettings,
    setStatusLine,
    settings,
    workspaceApi: desktopApi.workspace,
  });

  const {
    devMetrics,
    handleCopyDevMetricsSnapshot,
    handleResetDevMetrics,
    isDiagnosticsEnabled,
    isDevMetricsBusy,
    loadDevMetrics,
  } = useDiagnosticsWorkbench({
    copyToClipboard: handleCopyToClipboard,
    diagnosticsApi: desktopApi.diagnostics,
    isDevEnv,
    isWorkspaceSettingsOpen,
    nowIso: () => new Date().toISOString(),
    profileLabel: selectedProfile?.name || selectedProfileId || '-',
    runtimeApi: desktopApi.runtime,
    setStatusLine,
  });

  const {
    isListLoading,
    isNextPageDisabled,
    showGuidedStart,
  } = useWorkspaceRuntimeStateWorkbench({
    isBrowserBusy,
    isSearchBusy,
    selectedProfileId,
    nextAssetsContinuationToken,
    activeSearchQuery,
    hasInitialized,
  });

  const {
    activePendingDeleteJob,
    activeUploadJobCount,
    assetActionDialog,
    bulkDeleteDialogKeys,
    bulkMoveDialog,
    executePendingDelete,
    fileInputRef,
    handleCancelUpload,
    handleChangeAssetActionInputValue,
    handleChangeBulkMoveDestinationPrefix,
    handleClearFinishedUploads,
    handleCloseAssetActionDialog,
    handleCloseBulkDeleteDialog,
    handleCloseBulkMoveDialog,
    handleCloseUploadConflictDialog,
    handleFilePickerChange,
    handleOpenAssetDelete,
    handleOpenAssetMove,
    handleOpenAssetRename,
    handleOpenBulkDeleteDialog,
    handleOpenBulkMoveDialog,
    handleOpenFilePicker,
    handleResolveUploadConflict,
    handleRetryUpload,
    handleSubmitAssetAction,
    handleSubmitBulkDelete,
    handleSubmitBulkMove,
    isAssetActionBusy,
    isDropActive,
    isUploadBusy,
    isUploadToastExpanded,
    pendingDeleteQueuedMoreCount,
    pendingDeleteRemainingSeconds,
    setAssetActionDialog,
    setBulkDeleteDialogKeys,
    setBulkMoveDialog,
    setUploadConflictDialog,
    showPendingDeleteToast,
    showUploadToast,
    totalUploadJobs,
    undoPendingDelete,
    uploadConflictDialog,
    uploadSummaryCanRetry,
    uploadSummaryCompactTitle,
    uploadSummaryJob,
    uploadSummaryLastError,
    uploadSummaryProgress,
    uploadSummarySubtitle,
    uploadSummaryTitle,
  } = useAssetCommandFlowWorkbench({
    api: {
      assetLibrary: desktopApi.assetLibrary,
      assetUpload: desktopApi.assetUpload,
      files: desktopApi.files,
    },
    feedback: {
      pushInlineFeedback,
      setStatusLine,
    },
    gallery: {
      assetsPrefix,
      reloadCurrentItems,
      selectedAsset,
      selectedAssetKey,
      selectedAssetKeys,
      setIsSelectionMode,
      setSelectedAssetKey,
      setSelectedAssetKeys,
      visibleItems,
    },
    preview: {
      setIsQuickPreviewOpen,
    },
    surfaces: {
      appShellRef,
      uploadToastRef,
    },
    workspace: {
      defaultConflictPolicy: settings.defaultConflictPolicy,
      isConnectionSetupOpen,
      selectedProfileId,
      showGuidedStart,
    },
  });

  const {
    handleAssetItemClick,
    handleAssetItemDoubleClick,
    handleSelectAllVisible,
    toggleAssetSelection,
    toggleSelectionMode,
  } = useGallerySessionWorkbench({
    assetActionDialog,
    bulkDeleteDialogKeys,
    bulkMoveDialog,
    isPreviewableKind,
    isSelectionMode,
    loadAssetsPage,
    openQuickPreviewForItem,
    requestThumbnailRetry,
    resetAssetsResult,
    resetGalleryThumbnails,
    resetSearchState,
    resolvePersistedUiStateForProfile,
    selectedAssetKey,
    selectedProfileId,
    setAssetActionDialog,
    setAssetsPrefix,
    setBulkDeleteDialogKeys,
    setBulkMoveDialog,
    setGalleryScrollTop,
    setGalleryTileMinWidth,
    setIsSelectionMode,
    setKindFilter,
    setListScrollTop,
    setSelectedAssetKey,
    setSelectedAssetKeys,
    setSmartCollection,
    setSortBy,
    setSortDirection,
    setStatusLine,
    setViewMode,
    visibleItems,
  });

  const { shellProps, shellUi } = useDesktopWorkbenchShellCoordination(
    createDesktopWorkbenchShellCoordinationInput({
      activeKindFilter,
      activeSearchQuery,
      activeSmartCollection,
      assetActionDialog,
      assetItemRefs,
      assetsPrefix,
      bulkDeleteDialogKeys,
      bulkMoveDialog,
      closeQuickPreview,
      devMetrics,
      dismissStatusLine,
      focusAssetItemByKey,
      galleryColumnCount,
      galleryDaySections,
      galleryGridLocationByKey,
      galleryScrollRef,
      galleryTileHeight,
      galleryViewportHeight,
      galleryVirtualSections,
      handleCloseAssetActionDialog,
      handleCloseBulkDeleteDialog,
      handleCloseBulkMoveDialog,
      handleCloseConnectionSetup,
      handleCloseShortcutHelp,
      handleCloseUploadConflictDialog,
      handleCloseWorkspaceSettings,
      handleOpenAssetDelete,
      handleOpenBulkDeleteDialog,
      handleSelectAllVisible,
      handleToggleShortcutHelp,
      isConnectionSetupOpen,
      isDropActive,
      isQuickPreviewOpen,
      isSelectionMode,
      isShortcutHelpOpen,
      isTooltipWarm,
      isWorkspaceSettingsOpen,
      listVirtualItems,
      moveQuickPreviewSelection,
      openQuickPreviewForItem,
      resetGalleryTileMinWidth,
      searchInput,
      searchInputRef,
      selectedAsset,
      selectedAssetCount,
      selectedAssetKey,
      selectedProfileId,
      setGalleryTileMinWidth: adjustGalleryTileMinWidth,
      setIsWorkspaceSettingsOpen,
      setSelectedAssetKey,
      setUploadConflictDialog,
      showGuidedStart,
      status,
      statusTone,
      toggleAssetSelection,
      uploadConflictDialog,
      viewMode,
      visibleItems,
    }),
  );

  const {
    browserSession: workspaceSettingsBrowserSession,
    savedViews: workspaceSettingsSavedViews,
    viewDefaults: workspaceSettingsViewDefaults,
  } = useGallerySettingsWorkbench({
    activeKindFilter,
    activeSearchQuery,
    activeSmartCollection,
    assetsPrefix,
    browserPrefixes: assetsResult.prefixes,
    handleLoadFirstPage,
    handleLoadNextPage,
    handleOpenPrefix,
    isListLoading,
    isNextPageDisabled,
    isSearchBusy,
    loadAssetsPage,
    loadSavedViews,
    newSavedViewName,
    runSearch,
    savedViewApi: desktopApi.assetDiscovery,
    savedViews,
    searchInput,
    selectedProfileId,
    setAssetsPrefix,
    setIsSearchBusy,
    setKindFilter,
    setNewSavedViewName,
    setSearchInput,
    setSmartCollection,
    setSortBy,
    setSortDirection,
    setStatusLine,
    setViewMode,
    sortBy,
    sortDirection,
    viewMode,
  });

  const { workspaceSettingsOverlayProps } = useWorkspaceSettingsWorkbench(
    createDesktopWorkbenchWorkspaceSettingsCoordinationInput({
      browserSession: workspaceSettingsBrowserSession,
      cacheMetrics: {
        headCacheHitRate: shellUi.headCacheHitRate,
        previewCacheHitRate: shellUi.previewCacheHitRate,
        searchCacheHitRate: shellUi.searchCacheHitRate,
      },
      commands: {
        handleAppearanceChange,
        handleConnectionTest,
        handleDefaultConflictPolicyChange,
        handleOpenConnectionSetup,
        handlePresignedUrlTTLSecondsChange,
        handleSaveSettings,
        handleSelectedPublicBaseUrlChange,
        handleUploadOptimizeImagesBeforeUploadChange,
      },
      devMetrics: {
        devMetrics,
        handleCopyDevMetricsSnapshot,
        handleResetDevMetrics,
        isDevMetricsBusy,
        isDiagnosticsEnabled,
        loadDevMetrics,
      },
      gallerySettings: {
        savedViews: workspaceSettingsSavedViews,
        viewDefaults: workspaceSettingsViewDefaults,
      },
      modal: {
        cancelDiscardConfirmation,
        confirmDiscardChanges,
        handleCloseWorkspaceSettings,
        isSettingsDiscardConfirming: pendingDiscardConfirmation?.kind === 'settings',
        isWorkspaceSettingsOpen,
      },
      profile: {
        isProfileBusy,
        selectedProfile,
        selectedProfileId,
        selectedPublicBaseUrl,
      },
      settingsState: {
        isSettingsBusy,
        isSettingsDirty,
        settings,
      },
    }),
  );

  const appOverlaysProps = createDesktopWorkbenchOverlayCoordinationProps(
    createDesktopWorkbenchOverlayCoordinationInput({
      activePendingDeleteJob,
      activeUploadJobCount,
      allowStoredSecret,
      assetActionDialog,
      bulkDeleteDialogKeys,
      bulkMoveDialog,
      canSaveProfile,
      cancelDiscardConfirmation,
      confirmDiscardChanges,
      dropOverlayPrefixLabel: shellUi.dropOverlayPrefixLabel,
      executePendingDelete,
      handleCancelUpload,
      handleChangeAssetActionInputValue,
      handleChangeBulkMoveDestinationPrefix,
      handleClearFinishedUploads,
      handleCloseAssetActionDialog,
      handleCloseBulkDeleteDialog,
      handleCloseBulkMoveDialog,
      handleCloseConnectionSetup,
      handleCloseShortcutHelp,
      handleCloseUploadConflictDialog,
      handleDeleteProfile,
      handleOpenAssetDelete,
      handleOpenAssetMove,
      handleOpenAssetRename,
      handleR2AccountIdChange,
      handleResolveUploadConflict,
      handleRetryUpload,
      handleSaveProfile,
      handleStartNewProfile,
      handleSubmitAssetAction,
      handleSubmitBulkDelete,
      handleSubmitBulkMove,
      isAssetActionBusy,
      isConnectionSetupOpen,
      isCreatingProfile,
      isProfileDiscardConfirming: pendingDiscardConfirmation?.kind === 'profile',
      isDropActive,
      isProfileBusy,
      isShortcutHelpOpen,
      isUploadBusy,
      isUploadToastExpanded,
      pendingDeleteQueuedMoreCount,
      pendingDeleteRemainingSeconds,
      profileFieldErrors,
      profileForm,
      profileFormRefs,
      profileFormValidationErrors,
      quickPreviewOverlayInput,
      r2AccountId,
      selectedProfileId,
      setProfileForm,
      showPendingDeleteToast,
      showUploadToast,
      totalUploadJobs,
      undoPendingDelete,
      uploadConflictDialog,
      uploadSummaryCanRetry,
      uploadSummaryCompactTitle,
      uploadSummaryJob,
      uploadSummaryLastError,
      uploadSummaryProgress,
      uploadSummarySubtitle,
      uploadSummaryTitle,
      uploadToastRef,
      workspaceSettingsOverlayProps,
    }),
  );
  const appTopbarProps = createDesktopWorkbenchTopbarCoordinationProps(
    createDesktopWorkbenchTopbarCoordinationInput({
      activeSearchQuery,
      closeProfileMenu,
      fileInputRef,
      handleFilePickerChange,
      handleOpenFilePicker,
      handleProfileMenuSelect,
      handleSearchClear,
      handleSearchSubmit,
      handleToggleShortcutHelp,
      handleToggleWorkspaceSettings,
      inlineFeedback,
      isDropActive,
      isProfileMenuOpen,
      isSearchBusy,
      isShortcutHelpOpen,
      isUploadBusy,
      isWorkspaceSettingsOpen,
      logoSrc,
      manageProfileOptionValue,
      moveProfileMenuActiveIndex,
      newProfileOptionValue,
      openProfileMenu,
      profileMenuActiveIndex,
      profileMenuButtonRef,
      profileMenuListRef,
      profileMenuOptions,
      searchInput,
      searchInputRef,
      selectedProfileId,
      selectedProfileLabel,
      setProfileMenuActiveIndex,
      setSearchInput,
      showGuidedStart,
    }),
  );
  const workspaceCenterPaneProps = createDesktopWorkbenchCenterPaneCoordinationProps(
    createDesktopWorkbenchCenterPaneCoordinationInput({
      activeKindLabel,
      activeSearchQuery,
      activeSmartCollectionLabel,
      activeUnifiedFilterId,
      applyGalleryTileMinWidth,
      canClearSearch: shellUi.canClearSearch,
      canResetFilters: shellUi.canResetFilters,
      commitGalleryTileMinWidth,
      emptyStateMode: shellUi.emptyStateMode,
      flushGalleryTileMinWidthCommit,
      galleryColumnCount,
      galleryDaySections,
      galleryRovingAssetKey: shellUi.galleryRovingAssetKey,
      galleryScrollRef,
      gallerySizeSliderRef,
      galleryThumbnailErrors,
      galleryThumbnailLoading,
      galleryThumbnails,
      galleryTileMinWidth,
      galleryVirtualRange,
      handleAssetItemClick,
      handleAssetItemDoubleClick,
      handleLoadFirstPage,
      handleOpenBulkDeleteDialog,
      handleOpenBulkMoveDialog,
      handleOpenFilePicker,
      handleResetViewFilters,
      handleSearchClear,
      handleSelectAllVisible,
      handleSelectProfile,
      handleSelectUnifiedFilter,
      handleStartNewProfile,
      handleThumbnailDecodeError,
      isAssetActionBusy,
      isGalleryScrolling,
      isListLoading,
      isQuickPreviewOpen,
      isSelectionMode,
      isUploadBusy,
      listContainerRef,
      listRovingAssetKey: shellUi.listRovingAssetKey,
      listVirtualItems,
      listVirtualRange: {
        listBottomSpacerHeight: listVirtualRange.bottomSpacerHeight,
        listTopSpacerHeight: listVirtualRange.topSpacerHeight,
      },
      profiles,
      queueGalleryScrollStateUpdate,
      queueListScrollStateUpdate,
      scheduleGalleryTileMinWidthCommit,
      selectedAssetCount,
      selectedAssetKey,
      selectedAssetKeySet,
      selectedProfileId,
      setAssetItemRef,
      setSelectedAssetKey,
      setSelectedAssetKeys,
      setViewMode,
      showGuidedStart,
      toggleSelectionMode,
      unifiedFilterOptions,
      viewMode,
      visibleGallerySections,
      visibleItems,
    }),
  );

  return {
    appShellClassName: shellProps.appShellClassName,
    appShellRef,
    appOverlaysProps,
    appTopbarProps,
    isWorkspaceFocused: shellProps.isWorkspaceFocused,
    isWorkspaceInert: shellProps.isWorkspaceInert,
    statusStripProps: shellProps.statusStripProps,
    workspaceCenterPaneProps,
  };
};
